import { MediaType } from "../types/media";

export default {
  exampleMediaItem: {
    backdropPath: "/2quGobxbtKu1WywX9y90fTbxsIW.jpg",
    cast: null,
    code: 117378,
    directors: null,
    favorite: false,
    genres: null,
    numberOfEpisodes: null,
    numberOfSeasons: null,
    overview:
      'Uma história de suspense centrada na pergunta-chave: "E se pudéssemos identificar antecipadamente os psicopatas?". Este drama conta a história do Jung Ba Reum, um policial novato em busca de justiça. A história segue Jung Ba Reum quando ele fica cara a cara com um psicopata louco que é assassino em série, cujos assassinatos implacáveis colocaram toda a nação em um caos. Então, depois de sobreviver ao seu encontro com este psicopata, a vida do Jung Ba Reum começa a mudar completamente.',
    popularity: 13.964,
    posterPath: "/l38PZlYba97ziaAsK3N3NPnQDtr.jpg",
    providers: null,
    ratingAverage: 8.3,
    ratingCount: 55,
    ratingUser: null,
    releaseFinal: null,
    releaseInitial: "2021-03-03",
    runtime: null,
    status: null,
    title: "Mouse",
    tmdbUrl: "https://www.themoviedb.org/tv/117378",
    watchStatus: null,
    __typename: "TV",
  },
  exampleEpisodeNumber: {
    season: 2,
    episode: 5,
  },
  exampleClassname: "ml-2",
  exampleEpisode: {
    airDate: "2014-11-15",
    code: 1048387,
    episodeNumber: 3,
    favorite: false,
    overview: "",
    ratingAverage: 10,
    seasonNumber: 1,
    stillPath: "/82FnB03dqAcAyh3mI0AuwwDUiJX.jpg",
    title: "Episódio 3",
    __typename: "Episode",
  },
  exampleImgSrc:
    "https://image.tmdb.org/t/p/w154/ibiGOAzumOIzCk8fHwv03jzYbj9.jpg",
  exampleTitle: "SIMILAR TITLES",
  exampleMediaPage: { results: [], totalPages: 0, __typename: "MediaPage" },
  exampleMedia: MediaType.Tv,
  exampleProgress: 2,
  exampleLimit: 104,
  exampleProvider: "Netflix",
  exampleLabels: [
    "Albanian",
    "Arabic (Saudi Arabia)",
    "Arabic (United Arab Emirates)",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bulgarian",
    "Cantonese",
    "Catalan",
    "Chamorro",
    "Chinese (China)",
    "Chinese (Hong Kong)",
    "Chinese (Taiwan)",
    "Czech",
    "Danish",
    "Dutch",
    "English (Australia)",
    "English (Canada)",
    "English (Ireland)",
    "English (New Zealand)",
    "English (United Kingdom)",
    "English (United States)",
    "Esperanto",
    "Estonian",
    "Farsi",
    "Finnish",
    "French (Canada)",
    "French (France)",
    "Galician",
    "Georgian",
    "German (Austria)",
    "German (Germany)",
    "German (Switzerland)",
    "Greek",
    "Hebrew",
    "Hindi",
    "Hungarian",
    "Indonesian",
    "Italian",
    "Japanese",
    "Kannada",
    "Kazakh",
    "Korean",
    "Latvian",
    "Lithuanian",
    "Malay (Malaysia)",
    "Malay (Singapore)",
    "Malayalam",
    "Norwegian",
    "Norwegian",
    "Polish",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Romanian",
    "Russian",
    "Serbian",
    "Sinhala",
    "Slovak",
    "Slovenian",
    "Spanish (Mexico)",
    "Spanish (Spain)",
    "Swedish",
    "Tagalog",
    "Tamil",
    "Telugu",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Vietnamese",
    "Zulu",
  ],
  exampleOptions: [
    "sq-AL",
    "ar-SA",
    "ar-AE",
    "eu-ES",
    "be-BY",
    "bn-BD",
    "bg-BG",
    "cn-CN",
    "ca-ES",
    "ch-GU",
    "zh-CN",
    "zh-HK",
    "zh-TW",
    "cs-CZ",
    "da-DK",
    "nl-NL",
    "en-AU",
    "en-CA",
    "en-IE",
    "en-NZ",
    "en-GB",
    "en-US",
    "eo-EO",
    "et-EE",
    "fa-IR",
    "fi-FI",
    "fr-CA",
    "fr-FR",
    "gl-ES",
    "ka-GE",
    "de-AT",
    "de-DE",
    "de-CH",
    "el-GR",
    "he-IL",
    "hi-IN",
    "hu-HU",
    "id-ID",
    "it-IT",
    "ja-JP",
    "kn-IN",
    "kk-KZ",
    "ko-KR",
    "lv-LV",
    "lt-LT",
    "ms-MY",
    "ms-SG",
    "ml-IN",
    "nb-NO",
    "no-NO",
    "pl-PL",
    "pt-BR",
    "pt-PT",
    "ro-RO",
    "ru-RU",
    "sr-RS",
    "si-LK",
    "sk-SK",
    "sl-SI",
    "es-MX",
    "es-ES",
    "sv-SE",
    "tl-PH",
    "ta-IN",
    "te-IN",
    "th-TH",
    "tr-TR",
    "uk-UA",
    "vi-VN",
    "zu-ZA",
  ],
  exampleName: "language",
  exampleValue: "pt-BR",
};
