export const Country = [
  { englishName: "Afghanistan", nativeName: "Afghanistan", iso: "AF" },
  { englishName: "Albania", nativeName: "Albania", iso: "AL" },
  { englishName: "Algeria", nativeName: "Algeria", iso: "DZ" },
  { englishName: "American Samoa", nativeName: "American Samoa", iso: "AS" },
  { englishName: "Andorra", nativeName: "Andorra", iso: "AD" },
  { englishName: "Angola", nativeName: "Angola", iso: "AO" },
  { englishName: "Anguilla", nativeName: "Anguilla", iso: "AI" },
  { englishName: "Antarctica", nativeName: "Antarctica", iso: "AQ" },
  {
    englishName: "Antigua and Barbuda",
    nativeName: "Antigua & Barbuda",
    iso: "AG",
  },
  { englishName: "Argentina", nativeName: "Argentina", iso: "AR" },
  { englishName: "Armenia", nativeName: "Armenia", iso: "AM" },
  { englishName: "Aruba", nativeName: "Aruba", iso: "AW" },
  { englishName: "Australia", nativeName: "Australia", iso: "AU" },
  { englishName: "Austria", nativeName: "Austria", iso: "AT" },
  { englishName: "Azerbaijan", nativeName: "Azerbaijan", iso: "AZ" },
  { englishName: "Bahamas", nativeName: "Bahamas", iso: "BS" },
  { englishName: "Bahrain", nativeName: "Bahrain", iso: "BH" },
  { englishName: "Bangladesh", nativeName: "Bangladesh", iso: "BD" },
  { englishName: "Barbados", nativeName: "Barbados", iso: "BB" },
  { englishName: "Belarus", nativeName: "Belarus", iso: "BY" },
  { englishName: "Belgium", nativeName: "Belgium", iso: "BE" },
  { englishName: "Belize", nativeName: "Belize", iso: "BZ" },
  { englishName: "Benin", nativeName: "Benin", iso: "BJ" },
  { englishName: "Bermuda", nativeName: "Bermuda", iso: "BM" },
  { englishName: "Bhutan", nativeName: "Bhutan", iso: "BT" },
  { englishName: "Bolivia", nativeName: "Bolivia", iso: "BO" },
  {
    englishName: "Bosnia and Herzegovina",
    nativeName: "Bosnia & Herzegovina",
    iso: "BA",
  },
  { englishName: "Botswana", nativeName: "Botswana", iso: "BW" },
  { englishName: "Bouvet Island", nativeName: "Bouvet Island", iso: "BV" },
  { englishName: "Brazil", nativeName: "Brazil", iso: "BR" },
  {
    englishName: "British Indian Ocean Territory",
    nativeName: "British Indian Ocean Territory",
    iso: "IO",
  },
  {
    englishName: "British Virgin Islands",
    nativeName: "British Virgin Islands",
    iso: "VG",
  },
  { englishName: "Brunei Darussalam", nativeName: "Brunei", iso: "BN" },
  { englishName: "Bulgaria", nativeName: "Bulgaria", iso: "BG" },
  { englishName: "Burkina Faso", nativeName: "Burkina Faso", iso: "BF" },
  { englishName: "Burundi", nativeName: "Burundi", iso: "BI" },
  { englishName: "Cambodia", nativeName: "Cambodia", iso: "KH" },
  { englishName: "Cameroon", nativeName: "Cameroon", iso: "CM" },
  { englishName: "Canada", nativeName: "Canada", iso: "CA" },
  { englishName: "Cape Verde", nativeName: "Cape Verde", iso: "CV" },
  { englishName: "Cayman Islands", nativeName: "Cayman Islands", iso: "KY" },
  {
    englishName: "Central African Republic",
    nativeName: "Central African Republic",
    iso: "CF",
  },
  { englishName: "Chad", nativeName: "Chad", iso: "TD" },
  { englishName: "Chile", nativeName: "Chile", iso: "CL" },
  { englishName: "China", nativeName: "China", iso: "CN" },
  {
    englishName: "Christmas Island",
    nativeName: "Christmas Island",
    iso: "CX",
  },
  {
    englishName: "Cocos  Islands",
    nativeName: "Cocos (Keeling) Islands",
    iso: "CC",
  },
  { englishName: "Colombia", nativeName: "Colombia", iso: "CO" },
  { englishName: "Comoros", nativeName: "Comoros", iso: "KM" },
  {
    englishName: "Congo",
    nativeName: "Democratic Republic of the Congo (Kinshasa)",
    iso: "CD",
  },
  {
    englishName: "Congo",
    nativeName: "Republic of the Congo (Brazzaville)",
    iso: "CG",
  },
  { englishName: "Cook Islands", nativeName: "Cook Islands", iso: "CK" },
  { englishName: "Costa Rica", nativeName: "Costa Rica", iso: "CR" },
  { englishName: "Cote D'Ivoire", nativeName: "Côte d’Ivoire", iso: "CI" },
  { englishName: "Croatia", nativeName: "Croatia", iso: "HR" },
  { englishName: "Cuba", nativeName: "Cuba", iso: "CU" },
  { englishName: "Cyprus", nativeName: "Cyprus", iso: "CY" },
  { englishName: "Czech Republic", nativeName: "Czech Republic", iso: "CZ" },
  { englishName: "Czechoslovakia", nativeName: "Czechoslovakia", iso: "XC" },
  { englishName: "Denmark", nativeName: "Denmark", iso: "DK" },
  { englishName: "Djibouti", nativeName: "Djibouti", iso: "DJ" },
  { englishName: "Dominica", nativeName: "Dominica", iso: "DM" },
  {
    englishName: "Dominican Republic",
    nativeName: "Dominican Republic",
    iso: "DO",
  },
  { englishName: "East Germany", nativeName: "East Germany", iso: "XG" },
  { englishName: "Ecuador", nativeName: "Ecuador", iso: "EC" },
  { englishName: "Egypt", nativeName: "Egypt", iso: "EG" },
  { englishName: "El Salvador", nativeName: "El Salvador", iso: "SV" },
  {
    englishName: "Equatorial Guinea",
    nativeName: "Equatorial Guinea",
    iso: "GQ",
  },
  { englishName: "Eritrea", nativeName: "Eritrea", iso: "ER" },
  { englishName: "Estonia", nativeName: "Estonia", iso: "EE" },
  { englishName: "Ethiopia", nativeName: "Ethiopia", iso: "ET" },
  { englishName: "Faeroe Islands", nativeName: "Faroe Islands", iso: "FO" },
  {
    englishName: "Falkland Islands",
    nativeName: "Falkland Islands",
    iso: "FK",
  },
  { englishName: "Fiji", nativeName: "Fiji", iso: "FJ" },
  { englishName: "Finland", nativeName: "Finland", iso: "FI" },
  { englishName: "France", nativeName: "France", iso: "FR" },
  { englishName: "French Guiana", nativeName: "French Guiana", iso: "GF" },
  {
    englishName: "French Polynesia",
    nativeName: "French Polynesia",
    iso: "PF",
  },
  {
    englishName: "French Southern Territories",
    nativeName: "French Southern Territories",
    iso: "TF",
  },
  { englishName: "Gabon", nativeName: "Gabon", iso: "GA" },
  { englishName: "Gambia", nativeName: "Gambia", iso: "GM" },
  { englishName: "Georgia", nativeName: "Georgia", iso: "GE" },
  { englishName: "Germany", nativeName: "Germany", iso: "DE" },
  { englishName: "Ghana", nativeName: "Ghana", iso: "GH" },
  { englishName: "Gibraltar", nativeName: "Gibraltar", iso: "GI" },
  { englishName: "Greece", nativeName: "Greece", iso: "GR" },
  { englishName: "Greenland", nativeName: "Greenland", iso: "GL" },
  { englishName: "Grenada", nativeName: "Grenada", iso: "GD" },
  { englishName: "Guadaloupe", nativeName: "Guadeloupe", iso: "GP" },
  { englishName: "Guam", nativeName: "Guam", iso: "GU" },
  { englishName: "Guatemala", nativeName: "Guatemala", iso: "GT" },
  { englishName: "Guinea", nativeName: "Guinea", iso: "GN" },
  { englishName: "Guinea-Bissau", nativeName: "Guinea-Bissau", iso: "GW" },
  { englishName: "Guyana", nativeName: "Guyana", iso: "GY" },
  { englishName: "Haiti", nativeName: "Haiti", iso: "HT" },
  {
    englishName: "Heard and McDonald Islands",
    nativeName: "Heard & McDonald Islands",
    iso: "HM",
  },
  { englishName: "Holy See", nativeName: "Vatican City", iso: "VA" },
  { englishName: "Honduras", nativeName: "Honduras", iso: "HN" },
  { englishName: "Hong Kong", nativeName: "Hong Kong SAR China", iso: "HK" },
  { englishName: "Hungary", nativeName: "Hungary", iso: "HU" },
  { englishName: "Iceland", nativeName: "Iceland", iso: "IS" },
  { englishName: "India", nativeName: "India", iso: "IN" },
  { englishName: "Indonesia", nativeName: "Indonesia", iso: "ID" },
  { englishName: "Iran", nativeName: "Iran", iso: "IR" },
  { englishName: "Iraq", nativeName: "Iraq", iso: "IQ" },
  { englishName: "Ireland", nativeName: "Ireland", iso: "IE" },
  { englishName: "Israel", nativeName: "Israel", iso: "IL" },
  { englishName: "Italy", nativeName: "Italy", iso: "IT" },
  { englishName: "Jamaica", nativeName: "Jamaica", iso: "JM" },
  { englishName: "Japan", nativeName: "Japan", iso: "JP" },
  { englishName: "Jordan", nativeName: "Jordan", iso: "JO" },
  { englishName: "Kazakhstan", nativeName: "Kazakhstan", iso: "KZ" },
  { englishName: "Kenya", nativeName: "Kenya", iso: "KE" },
  { englishName: "Kiribati", nativeName: "Kiribati", iso: "KI" },
  { englishName: "Kosovo", nativeName: "Kosovo", iso: "XK" },
  { englishName: "Kuwait", nativeName: "Kuwait", iso: "KW" },
  { englishName: "Kyrgyz Republic", nativeName: "Kyrgyzstan", iso: "KG" },
  {
    englishName: "Lao People's Democratic Republic",
    nativeName: "Laos",
    iso: "LA",
  },
  { englishName: "Latvia", nativeName: "Latvia", iso: "LV" },
  { englishName: "Lebanon", nativeName: "Lebanon", iso: "LB" },
  { englishName: "Lesotho", nativeName: "Lesotho", iso: "LS" },
  { englishName: "Liberia", nativeName: "Liberia", iso: "LR" },
  { englishName: "Libyan Arab Jamahiriya", nativeName: "Libya", iso: "LY" },
  { englishName: "Liechtenstein", nativeName: "Liechtenstein", iso: "LI" },
  { englishName: "Lithuania", nativeName: "Lithuania", iso: "LT" },
  { englishName: "Luxembourg", nativeName: "Luxembourg", iso: "LU" },
  { englishName: "Macao", nativeName: "Macau SAR China", iso: "MO" },
  { englishName: "Macedonia", nativeName: "Macedonia", iso: "MK" },
  { englishName: "Madagascar", nativeName: "Madagascar", iso: "MG" },
  { englishName: "Malawi", nativeName: "Malawi", iso: "MW" },
  { englishName: "Malaysia", nativeName: "Malaysia", iso: "MY" },
  { englishName: "Maldives", nativeName: "Maldives", iso: "MV" },
  { englishName: "Mali", nativeName: "Mali", iso: "ML" },
  { englishName: "Malta", nativeName: "Malta", iso: "MT" },
  {
    englishName: "Marshall Islands",
    nativeName: "Marshall Islands",
    iso: "MH",
  },
  { englishName: "Martinique", nativeName: "Martinique", iso: "MQ" },
  { englishName: "Mauritania", nativeName: "Mauritania", iso: "MR" },
  { englishName: "Mauritius", nativeName: "Mauritius", iso: "MU" },
  { englishName: "Mayotte", nativeName: "Mayotte", iso: "YT" },
  { englishName: "Mexico", nativeName: "Mexico", iso: "MX" },
  { englishName: "Micronesia", nativeName: "Micronesia", iso: "FM" },
  { englishName: "Moldova", nativeName: "Moldova", iso: "MD" },
  { englishName: "Monaco", nativeName: "Monaco", iso: "MC" },
  { englishName: "Mongolia", nativeName: "Mongolia", iso: "MN" },
  { englishName: "Montenegro", nativeName: "Montenegro", iso: "ME" },
  { englishName: "Montserrat", nativeName: "Montserrat", iso: "MS" },
  { englishName: "Morocco", nativeName: "Morocco", iso: "MA" },
  { englishName: "Mozambique", nativeName: "Mozambique", iso: "MZ" },
  { englishName: "Myanmar", nativeName: "Myanmar (Burma)", iso: "MM" },
  { englishName: "Namibia", nativeName: "Namibia", iso: "NA" },
  { englishName: "Nauru", nativeName: "Nauru", iso: "NR" },
  { englishName: "Nepal", nativeName: "Nepal", iso: "NP" },
  { englishName: "Netherlands", nativeName: "Netherlands", iso: "NL" },
  {
    englishName: "Netherlands Antilles",
    nativeName: "Netherlands Antilles",
    iso: "AN",
  },
  { englishName: "New Caledonia", nativeName: "New Caledonia", iso: "NC" },
  { englishName: "New Zealand", nativeName: "New Zealand", iso: "NZ" },
  { englishName: "Nicaragua", nativeName: "Nicaragua", iso: "NI" },
  { englishName: "Niger", nativeName: "Niger", iso: "NE" },
  { englishName: "Nigeria", nativeName: "Nigeria", iso: "NG" },
  { englishName: "Niue", nativeName: "Niue", iso: "NU" },
  { englishName: "Norfolk Island", nativeName: "Norfolk Island", iso: "NF" },
  { englishName: "North Korea", nativeName: "North Korea", iso: "KP" },
  {
    englishName: "Northern Mariana Islands",
    nativeName: "Northern Mariana Islands",
    iso: "MP",
  },
  { englishName: "Norway", nativeName: "Norway", iso: "NO" },
  { englishName: "Oman", nativeName: "Oman", iso: "OM" },
  { englishName: "Pakistan", nativeName: "Pakistan", iso: "PK" },
  { englishName: "Palau", nativeName: "Palau", iso: "PW" },
  {
    englishName: "Palestinian Territory",
    nativeName: "Palestinian Territories",
    iso: "PS",
  },
  { englishName: "Panama", nativeName: "Panama", iso: "PA" },
  {
    englishName: "Papua New Guinea",
    nativeName: "Papua New Guinea",
    iso: "PG",
  },
  { englishName: "Paraguay", nativeName: "Paraguay", iso: "PY" },
  { englishName: "Peru", nativeName: "Peru", iso: "PE" },
  { englishName: "Philippines", nativeName: "Philippines", iso: "PH" },
  { englishName: "Pitcairn Island", nativeName: "Pitcairn Islands", iso: "PN" },
  { englishName: "Poland", nativeName: "Poland", iso: "PL" },
  { englishName: "Portugal", nativeName: "Portugal", iso: "PT" },
  { englishName: "Puerto Rico", nativeName: "Puerto Rico", iso: "PR" },
  { englishName: "Qatar", nativeName: "Qatar", iso: "QA" },
  { englishName: "Reunion", nativeName: "Réunion", iso: "RE" },
  { englishName: "Romania", nativeName: "Romania", iso: "RO" },
  { englishName: "Russia", nativeName: "Russia", iso: "RU" },
  { englishName: "Rwanda", nativeName: "Rwanda", iso: "RW" },
  { englishName: "Samoa", nativeName: "Samoa", iso: "WS" },
  { englishName: "San Marino", nativeName: "San Marino", iso: "SM" },
  {
    englishName: "Sao Tome and Principe",
    nativeName: "São Tomé & Príncipe",
    iso: "ST",
  },
  { englishName: "Saudi Arabia", nativeName: "Saudi Arabia", iso: "SA" },
  { englishName: "Senegal", nativeName: "Senegal", iso: "SN" },
  { englishName: "Serbia", nativeName: "Serbia", iso: "RS" },
  {
    englishName: "Serbia and Montenegro",
    nativeName: "Serbia and Montenegro",
    iso: "CS",
  },
  { englishName: "Seychelles", nativeName: "Seychelles", iso: "SC" },
  { englishName: "Sierra Leone", nativeName: "Sierra Leone", iso: "SL" },
  { englishName: "Singapore", nativeName: "Singapore", iso: "SG" },
  { englishName: "Slovakia", nativeName: "Slovakia", iso: "SK" },
  { englishName: "Slovenia", nativeName: "Slovenia", iso: "SI" },
  { englishName: "Solomon Islands", nativeName: "Solomon Islands", iso: "SB" },
  { englishName: "Somalia", nativeName: "Somalia", iso: "SO" },
  { englishName: "South Africa", nativeName: "South Africa", iso: "ZA" },
  {
    englishName: "South Georgia and the South Sandwich Islands",
    nativeName: "South Georgia & South Sandwich Islands",
    iso: "GS",
  },
  { englishName: "South Korea", nativeName: "South Korea", iso: "KR" },
  { englishName: "South Sudan", nativeName: "South Sudan", iso: "SS" },
  { englishName: "Soviet Union", nativeName: "Soviet Union", iso: "SU" },
  { englishName: "Spain", nativeName: "Spain", iso: "ES" },
  { englishName: "Sri Lanka", nativeName: "Sri Lanka", iso: "LK" },
  { englishName: "St. Helena", nativeName: "St. Helena", iso: "SH" },
  {
    englishName: "St. Kitts and Nevis",
    nativeName: "St. Kitts & Nevis",
    iso: "KN",
  },
  { englishName: "St. Lucia", nativeName: "St. Lucia", iso: "LC" },
  {
    englishName: "St. Pierre and Miquelon",
    nativeName: "St. Pierre & Miquelon",
    iso: "PM",
  },
  {
    englishName: "St. Vincent and the Grenadines",
    nativeName: "St. Vincent & Grenadines",
    iso: "VC",
  },
  { englishName: "Sudan", nativeName: "Sudan", iso: "SD" },
  { englishName: "Suriname", nativeName: "Suriname", iso: "SR" },
  {
    englishName: "Svalbard & Jan Mayen Islands",
    nativeName: "Svalbard & Jan Mayen",
    iso: "SJ",
  },
  { englishName: "Swaziland", nativeName: "Eswatini (Swaziland)", iso: "SZ" },
  { englishName: "Sweden", nativeName: "Sweden", iso: "SE" },
  { englishName: "Switzerland", nativeName: "Switzerland", iso: "CH" },
  { englishName: "Syrian Arab Republic", nativeName: "Syria", iso: "SY" },
  { englishName: "Taiwan", nativeName: "Taiwan", iso: "TW" },
  { englishName: "Tajikistan", nativeName: "Tajikistan", iso: "TJ" },
  { englishName: "Tanzania", nativeName: "Tanzania", iso: "TZ" },
  { englishName: "Thailand", nativeName: "Thailand", iso: "TH" },
  { englishName: "Timor-Leste", nativeName: "Timor-Leste", iso: "TL" },
  { englishName: "Togo", nativeName: "Togo", iso: "TG" },
  { englishName: "Tokelau", nativeName: "Tokelau", iso: "TK" },
  { englishName: "Tonga", nativeName: "Tonga", iso: "TO" },
  {
    englishName: "Trinidad and Tobago",
    nativeName: "Trinidad & Tobago",
    iso: "TT",
  },
  { englishName: "Tunisia", nativeName: "Tunisia", iso: "TN" },
  { englishName: "Turkey", nativeName: "Turkey", iso: "TR" },
  { englishName: "Turkmenistan", nativeName: "Turkmenistan", iso: "TM" },
  {
    englishName: "Turks and Caicos Islands",
    nativeName: "Turks & Caicos Islands",
    iso: "TC",
  },
  { englishName: "Tuvalu", nativeName: "Tuvalu", iso: "TV" },
  { englishName: "Uganda", nativeName: "Uganda", iso: "UG" },
  { englishName: "Ukraine", nativeName: "Ukraine", iso: "UA" },
  {
    englishName: "United Arab Emirates",
    nativeName: "United Arab Emirates",
    iso: "AE",
  },
  { englishName: "United Kingdom", nativeName: "United Kingdom", iso: "GB" },
  {
    englishName: "United States Minor Outlying Islands",
    nativeName: "U.S. Outlying Islands",
    iso: "UM",
  },
  {
    englishName: "United States of America",
    nativeName: "United States",
    iso: "US",
  },
  { englishName: "Uruguay", nativeName: "Uruguay", iso: "UY" },
  {
    englishName: "US Virgin Islands",
    nativeName: "U.S. Virgin Islands",
    iso: "VI",
  },
  { englishName: "Uzbekistan", nativeName: "Uzbekistan", iso: "UZ" },
  { englishName: "Vanuatu", nativeName: "Vanuatu", iso: "VU" },
  { englishName: "Venezuela", nativeName: "Venezuela", iso: "VE" },
  { englishName: "Vietnam", nativeName: "Vietnam", iso: "VN" },
  {
    englishName: "Wallis and Futuna Islands",
    nativeName: "Wallis & Futuna",
    iso: "WF",
  },
  { englishName: "Western Sahara", nativeName: "Western Sahara", iso: "EH" },
  { englishName: "Yemen", nativeName: "Yemen", iso: "YE" },
  { englishName: "Yugoslavia", nativeName: "Yugoslavia", iso: "YU" },
  { englishName: "Zambia", nativeName: "Zambia", iso: "ZM" },
  { englishName: "Zimbabwe", nativeName: "Zimbabwe", iso: "ZW" },
];
