export const Language = [
  { englishName: "Albanian", iso: "sq-AL" },
  { englishName: "Arabic (Saudi Arabia)", iso: "ar-SA" },
  { englishName: "Arabic (United Arab Emirates)", iso: "ar-AE" },
  { englishName: "Basque", iso: "eu-ES" },
  { englishName: "Belarusian", iso: "be-BY" },
  { englishName: "Bengali", iso: "bn-BD" },
  { englishName: "Bulgarian", iso: "bg-BG" },
  { englishName: "Cantonese", iso: "cn-CN" },
  { englishName: "Catalan", iso: "ca-ES" },
  { englishName: "Chamorro", iso: "ch-GU" },
  { englishName: "Chinese (China)", iso: "zh-CN" },
  { englishName: "Chinese (Hong Kong)", iso: "zh-HK" },
  { englishName: "Chinese (Taiwan)", iso: "zh-TW" },
  { englishName: "Czech", iso: "cs-CZ" },
  { englishName: "Danish", iso: "da-DK" },
  { englishName: "Dutch", iso: "nl-NL" },
  { englishName: "English (Australia)", iso: "en-AU" },
  { englishName: "English (Canada)", iso: "en-CA" },
  { englishName: "English (Ireland)", iso: "en-IE" },
  { englishName: "English (New Zealand)", iso: "en-NZ" },
  { englishName: "English (United Kingdom)", iso: "en-GB" },
  { englishName: "English (United States)", iso: "en-US" },
  { englishName: "Esperanto", iso: "eo-EO" },
  { englishName: "Estonian", iso: "et-EE" },
  { englishName: "Farsi", iso: "fa-IR" },
  { englishName: "Finnish", iso: "fi-FI" },
  { englishName: "French (Canada)", iso: "fr-CA" },
  { englishName: "French (France)", iso: "fr-FR" },
  { englishName: "Galician", iso: "gl-ES" },
  { englishName: "Georgian", iso: "ka-GE" },
  { englishName: "German (Austria)", iso: "de-AT" },
  { englishName: "German (Germany)", iso: "de-DE" },
  { englishName: "German (Switzerland)", iso: "de-CH" },
  { englishName: "Greek", iso: "el-GR" },
  { englishName: "Hebrew", iso: "he-IL" },
  { englishName: "Hindi", iso: "hi-IN" },
  { englishName: "Hungarian", iso: "hu-HU" },
  { englishName: "Indonesian", iso: "id-ID" },
  { englishName: "Italian", iso: "it-IT" },
  { englishName: "Japanese", iso: "ja-JP" },
  { englishName: "Kannada", iso: "kn-IN" },
  { englishName: "Kazakh", iso: "kk-KZ" },
  { englishName: "Korean", iso: "ko-KR" },
  { englishName: "Latvian", iso: "lv-LV" },
  { englishName: "Lithuanian", iso: "lt-LT" },
  { englishName: "Malay (Malaysia)", iso: "ms-MY" },
  { englishName: "Malay (Singapore)", iso: "ms-SG" },
  { englishName: "Malayalam", iso: "ml-IN" },
  { englishName: "Norwegian", iso: "nb-NO" },
  { englishName: "Norwegian", iso: "no-NO" },
  { englishName: "Polish", iso: "pl-PL" },
  { englishName: "Portuguese (Brazil)", iso: "pt-BR" },
  { englishName: "Portuguese (Portugal)", iso: "pt-PT" },
  { englishName: "Romanian", iso: "ro-RO" },
  { englishName: "Russian", iso: "ru-RU" },
  { englishName: "Serbian", iso: "sr-RS" },
  { englishName: "Sinhala", iso: "si-LK" },
  { englishName: "Slovak", iso: "sk-SK" },
  { englishName: "Slovenian", iso: "sl-SI" },
  { englishName: "Spanish (Mexico)", iso: "es-MX" },
  { englishName: "Spanish (Spain)", iso: "es-ES" },
  { englishName: "Swedish", iso: "sv-SE" },
  { englishName: "Tagalog", iso: "tl-PH" },
  { englishName: "Tamil", iso: "ta-IN" },
  { englishName: "Telugu", iso: "te-IN" },
  { englishName: "Thai", iso: "th-TH" },
  { englishName: "Turkish", iso: "tr-TR" },
  { englishName: "Ukrainian", iso: "uk-UA" },
  { englishName: "Vietnamese", iso: "vi-VN" },
  { englishName: "Zulu", iso: "zu-ZA" },
];
